# User config
author: "YESEUL KIM"
tagline: "portfolio page"
description: "Python, Django Back-end developer. <br> other interests: Database, SQL, data analysis, data visualization, UX design, interaction design."
keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "admirebg@gmail.com"
linkedin: ""
github: "https://github.com/admirebg"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed