# User config
author: "YESEUL KIM"
tagline: "portfolio page"
description: "SW engineer, Back-end developer, and interested in data engineer"
keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "admirebg@gmail.com"
linkedin: ""
github: "https://github.com/admirebg"

# Site config
baseurl: "/portfolio"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed